### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "9e9d609e49624db8bad4e5482366f51a",
  "accountNumber": "1000000002",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/f251f25d2fad43929ce6fc8ea24a3fab